### ISSUE TITLE
Shape of `chain` and `lnprobabilty` attributes are not consistent

### ISSUE THREAD

**Issue by uweschmitt** [dfm/emcee3#6]
Using `emcee2` I get the following shapes after sampling:

`sampler.chain`: `(30, 100, 3)`
 `sampler.lnprobability`: `(30, 100)`

Using the latest version `3.0rc2` the shapes are:

`sampler.chain`: `(30, 100, 3)`
 `sampler.lnprobability`: `(100, 30)`

So the shape of `chain` stayed the same, but new current shape of `lnprobability` is not consistent anymore.

**Comment by dfm** [comment]
I know it's a bit confusing, but this project is actually a separate project from dfm/emcee and the version `3.0rc2` is actually implemented there. This bug has just been fixed over there: https://github.com/dfm/emcee/pull/295

Thanks!
